# Generated by Django 4.2.3 on 2023-12-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('kind', models.CharField(max_length=255, verbose_name='Вид')),
                ('image', models.ImageField(null=True, upload_to='bestiary/images/', verbose_name='Изображение')),
                ('ac', models.IntegerField(verbose_name='Класс брони')),
                ('hp', models.IntegerField(verbose_name='Очки здоровья')),
                ('strength', models.IntegerField(verbose_name='Сила')),
                ('dexterity', models.IntegerField(verbose_name='Ловкость')),
                ('constitution', models.IntegerField(verbose_name='Телосложение')),
                ('intelligence', models.IntegerField(verbose_name='Интеллект')),
                ('wisdom', models.IntegerField(verbose_name='Мудрость')),
                ('charisma', models.IntegerField(verbose_name='Харизма')),
                ('experience', models.IntegerField(verbose_name='Опыт')),
            ],
        ),
    ]
