# Generated by Django 4.1.7 on 2023-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('race', models.CharField(choices=[('Дварф', 'Дварф'), ('Эльф', 'Эльф'), ('Полурослик', 'Полурослик'), ('Человек', 'Человек'), ('Драконорожденный', 'Драконорожденный'), ('Гном', 'Гном'), ('Полуэльф', 'Полуэльф'), ('Полуорк', 'Полуорк'), ('Тифлинг', 'Тифлинг')], max_length=20, verbose_name='Раса')),
                ('ideology', models.CharField(choices=[('Законно - добрый', 'Законно - добрый'), ('Нейтрально - добрый', 'Нейтрально - добрый'), ('Хаотично - добрый', 'Хаотично - добрый'), ('Законно - нейтральный', 'Законно - нейтральный'), ('Нейтральный', 'Нейтральный'), ('Хаотично - нейтральный', 'Хаотично - нейтральный'), ('Законно - злой', 'Законно - злой'), ('Нейтрально - злой', 'Нейтрально - злой'), ('Хаотично - злой', 'Хаотично - злой')], max_length=50, verbose_name='Мировоззрение')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание персонажа')),
                ('gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=20, verbose_name='Пол')),
                ('portrait', models.ImageField(upload_to='portraits/', verbose_name='Портрет')),
                ('strenght', models.IntegerField(verbose_name='Сила')),
                ('dexterity', models.IntegerField(verbose_name='Ловкость')),
                ('constitution', models.IntegerField(verbose_name='Телосложение')),
                ('intellect', models.IntegerField(verbose_name='Интеллект')),
                ('wizdom', models.IntegerField(verbose_name='Мудрость')),
                ('charisma', models.IntegerField(verbose_name='Харизма')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карточка персонажа',
                'verbose_name_plural': 'Карточки персонажей',
                'ordering': ['time_create'],
            },
        ),
    ]
