# Generated by Django 4.2.3 on 2023-12-15 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestiary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enemy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='bestiary.bestiary')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_num', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Действие')),
                ('action_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Детализация действия')),
                ('action_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат действия')),
                ('winner', models.CharField(blank=True, max_length=255, null=True, verbose_name='Победитель')),
                ('battle_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат боя')),
                ('battle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='arena.arena')),
            ],
        ),
    ]
